### ISSUE TITLE
TwitterのAPIについて調べる。

### ISSUE THREAD

**Issue by gotoh-poclab** [Mod12d/relation-app#7]
汚染されたUserを調べるために何が使えるのかを調べてみる。

https://developer.twitter.com/en/docs/twitter-api/v1/accounts-and-users/mute-block-report-users/api-reference/get-mutes-users-list

**Comment by gotoh-poclab** [comment]
twitterのapiや、それをpythonで扱えるtweepyで調べたものです。
APIだけでできるものとかはなくて、人が使う操作を自動化したりたくさんの情報を取得できるようになるのかなと思います。

# muteやblock関係
自分がミュートしているとかブロックしているかは取得できるが、別のユーザーに代わってアクションを実行するには、そのユーザーのアクセストークンを取得する必要がありそう。

https://kurozumi.github.io/tweepy/auth_tutorial.html

いろんな人がブロックしているやミュートしているなどの情報取得は難しそう。

# フォローワーやフォローしている人
この情報は、その人出なくても取得できるし、フォロワーのフォロワーなどと追っていける。あと相互にフォローしているかも確認可能。
```api.get_followers```
で取得だと20件だが、別の書き方で制限時間などを調整しながら行えば全件も取得できる。
```tweepy.Cursor```

# タイムラインの情報
どんなことを呟いているか、いいねの数、リツイートの数などの取得も簡単。

**Comment by Mod12d** [comment]
ありがとうございます!! 🚀 
汚染ユーザは、個別のユーザ情報から判定していく方法が良さそうですね。。。

自分がmuteしてたりblockしてるユーザを教師データに、フォロワーに類似ユーザがいるか判定する方法もあるかなとふと思いました。

**Comment by Mod12d** [comment]
@gotoh-poclab 
おつかれさまです！
遅くなってすみません 🙇🏻‍♂️ 
#13 に調べてみたことを書きました 🙏🏻
